# Generated by Codex for P1 用户权限底座.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=64)),
                ("password_hash", models.CharField(max_length=255)),
                ("role", models.CharField(choices=[("admin", "管理人员"), ("member", "普通成员")], default="member", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "user_account", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=255, unique=True)),
                ("role", models.CharField(choices=[("admin", "管理人员"), ("member", "普通成员")], default="member", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[("unused", "未使用"), ("used", "已使用"), ("revoked", "已作废"), ("expired", "已过期")],
                        default="unused",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_invitations", to="accounts.useraccount"),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_invitations",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_invitations",
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={"db_table": "invitation_code", "ordering": ["-created_at", "-id"]},
        ),
    ]
