# Generated by Codex for Stage3 P2 测试数据底座与只读通过率页面.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestEnvironment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("env_key", models.CharField(max_length=64, unique=True)),
                ("env_name", models.CharField(db_index=True, max_length=128)),
                ("base_url", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "test_environment", "ordering": ["env_name", "id"]},
        ),
        migrations.CreateModel(
            name="TestModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("package_name", models.CharField(max_length=128, unique=True)),
                ("case_path", models.CharField(db_index=True, max_length=512)),
                ("module_name", models.CharField(db_index=True, max_length=128)),
                ("module_dev", models.CharField(db_index=True, max_length=128)),
                ("module_test", models.CharField(db_index=True, max_length=128)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "test_module", "ordering": ["package_name", "id"]},
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_key", models.CharField(max_length=128, unique=True)),
                (
                    "run_type",
                    models.CharField(
                        choices=[("daily_full", "每日全量"), ("module_rerun", "模块重试"), ("failed_rerun", "失败重试")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "排队中"), ("running", "执行中"), ("success", "成功"), ("failed", "失败"), ("canceled", "已取消")],
                        db_index=True,
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("duration_seconds", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("summary_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="metrics.testenvironment"),
                ),
                (
                    "module",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="metrics.testmodule"),
                ),
            ],
            options={"db_table": "test_run", "ordering": ["-started_at", "-id"]},
        ),
        migrations.CreateModel(
            name="EnvironmentSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("total_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("passed_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("pass_rate", models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="snapshot", to="metrics.testenvironment"),
                ),
                (
                    "latest_run",
                    models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="metrics.testrun"),
                ),
            ],
            options={"db_table": "environment_snapshot", "ordering": ["environment_id"]},
        ),
        migrations.CreateModel(
            name="ModuleSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("duration_seconds", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("total_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(db_index=True, default=0)),
                ("passed_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("pass_rate", models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="metrics.testenvironment")),
                ("latest_run", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="metrics.testrun")),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="metrics.testmodule")),
            ],
            options={
                "db_table": "module_snapshot",
                "ordering": ["pass_rate", "-completed_at", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("environment", "module"), name="uniq_module_snapshot_environment_module"),
                ],
            },
        ),
    ]
