# Generated by Django 5.2.15 on 2026-07-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=1024)),
                ('current_node_key', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('case_name', models.CharField(db_index=True, max_length=256)),
                ('case_summary', models.CharField(blank=True, max_length=512)),
                ('assertion_text', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, db_index=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('error_message_summary', models.CharField(blank=True, max_length=512)),
                ('execution_status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('skipped', '跳过'), ('error', '错误')], db_index=True, max_length=32)),
                ('display_status', models.CharField(choices=[('failed', '失败'), ('passed', '通过'), ('skipped', '跳过'), ('archived', '已归档')], db_index=True, default='failed', max_length=32)),
                ('confirmation_result', models.CharField(blank=True, max_length=128)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testenvironment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testmodule')),
                ('module_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='metrics.modulesnapshot')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.testrun')),
            ],
            options={
                'db_table': 'test_case_result',
                'ordering': ['display_status', '-occurred_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('environment', 'module', 'current_node_key'), name='uniq_current_case_result_env_module_node')],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.CharField(max_length=512)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_status_audits', to='accounts.useraccount')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.testenvironment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.testmodule')),
                ('case_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_audits', to='metrics.testcaseresult')),
            ],
            options={
                'db_table': 'case_status_audit',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleRunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True)),
                ('run_type', models.CharField(choices=[('daily_full', '每日全量'), ('module_rerun', '模块重试'), ('failed_rerun', '失败重试')], db_index=True, default='daily_full', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('passed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('pass_rate', models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testenvironment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testmodule')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.testrun')),
            ],
            options={
                'db_table': 'module_run_history',
                'ordering': ['run_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('environment', 'module', 'run_date', 'run_type', 'source_run'), name='uniq_module_history_env_module_date_run')],
            },
        ),
        migrations.AddIndex(
            model_name='testcaseresult',
            index=models.Index(fields=['environment', 'module', 'display_status'], name='idx_case_env_module_status'),
        ),
        migrations.AddIndex(
            model_name='testcaseresult',
            index=models.Index(fields=['module_snapshot', 'is_current', 'display_status'], name='idx_case_snapshot_current'),
        ),
    ]
