# Generated by Django 5.2.15 on 2026-07-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('metrics', '0002_testcaseresult_casestatusaudit_modulerunhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('success', '成功'), ('test_failed', '用例失败'), ('failed', '失败'), ('canceling', '取消中'), ('canceled', '已取消')], db_index=True, default='queued', max_length=32),
        ),
        migrations.CreateModel(
            name='JenkinsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('daily_full', '每日全量'), ('module_rerun', '模块重试'), ('failed_rerun', '失败重试')], db_index=True, max_length=32)),
                ('trigger_source', models.CharField(choices=[('platform_user', '平台用户'), ('jenkins_cron', 'Jenkins 定时'), ('manual_sync', '手动同步')], db_index=True, default='platform_user', max_length=32)),
                ('job_full_name', models.CharField(db_index=True, max_length=255)),
                ('queue_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('build_number', models.IntegerField(blank=True, null=True)),
                ('jenkins_queue_url', models.CharField(blank=True, max_length=1024)),
                ('jenkins_build_url', models.CharField(blank=True, max_length=1024)),
                ('artifact_base_url', models.CharField(blank=True, max_length=1024)),
                ('summary_artifact_url', models.CharField(blank=True, max_length=1024)),
                ('failed_nodeids_artifact_url', models.CharField(blank=True, max_length=1024)),
                ('allure_report_url', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('success', '成功'), ('test_failed', '用例失败'), ('failed', '失败'), ('canceling', '取消中'), ('canceled', '已取消')], db_index=True, default='queued', max_length=32)),
                ('jenkins_result', models.CharField(blank=True, max_length=64)),
                ('requested_nodeids_json', models.JSONField(blank=True, default=list)),
                ('summary_json', models.JSONField(blank=True, null=True)),
                ('failed_nodeids_json', models.JSONField(blank=True, default=list)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.testenvironment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.testmodule')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.testrun')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jenkins_tasks', to='accounts.useraccount')),
            ],
            options={
                'db_table': 'jenkins_task',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleExecutionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_type', models.CharField(default='module_execution', max_length=32)),
                ('status', models.CharField(choices=[('active', '生效中'), ('released', '已释放'), ('expired', '已过期')], db_index=True, default='active', max_length=32)),
                ('active_lock_key', models.CharField(blank=True, max_length=128, null=True)),
                ('locked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testenvironment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testmodule')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_locks', to='metrics.jenkinstask')),
            ],
            options={
                'db_table': 'module_execution_lock',
                'ordering': ['-locked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JenkinsJobBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('daily_full', '每日全量'), ('module_rerun', '模块重试'), ('failed_rerun', '失败重试')], db_index=True, max_length=32)),
                ('job_full_name', models.CharField(db_index=True, max_length=255)),
                ('default_retry_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testenvironment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.testmodule')),
            ],
            options={
                'db_table': 'jenkins_job_binding',
                'ordering': ['environment_id', 'module_id', 'task_type'],
                'constraints': [models.UniqueConstraint(fields=('environment', 'module', 'task_type'), name='uniq_jenkins_job_binding_env_module_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='jenkinstask',
            constraint=models.UniqueConstraint(fields=('job_full_name', 'build_number'), name='uniq_jenkins_task_job_build'),
        ),
        migrations.AddConstraint(
            model_name='moduleexecutionlock',
            constraint=models.UniqueConstraint(fields=('active_lock_key',), name='uniq_active_module_execution_lock'),
        ),
    ]
