[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts =
    --reuse-db
    --nomigrations
    --strict-markers
markers =
    slow: 标记为慢速测试
    integration: 标记为集成测试
