# Generated by Django 5.2.15 on 2026-06-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(db_index=True, max_length=128, verbose_name='模块标识')),
                ('module_name', models.CharField(max_length=255, verbose_name='模块展示名')),
                ('case_path', models.CharField(max_length=512, verbose_name='用例文件路径')),
                ('node_id', models.CharField(max_length=512, unique=True, verbose_name='pytest node id')),
                ('function_name', models.CharField(max_length=255, verbose_name='测试函数名')),
                ('class_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试类名')),
                ('case_title', models.CharField(blank=True, default='', max_length=512, verbose_name='用例标题')),
                ('story', models.CharField(blank=True, default='', max_length=255, verbose_name='story')),
                ('severity', models.CharField(blank=True, default='', max_length=32, verbose_name='severity')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('synced_at', models.DateTimeField(verbose_name='最近同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用例快照',
                'verbose_name_plural': '用例快照',
                'db_table': 'testcases_testcasesnapshot',
                'ordering': ['module_key', 'node_id'],
            },
        ),
    ]
